version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB_HOST: ${{ secrets.DB_HOST }}
      POSTGRES_DB_PORT: ${{ secrets.DB_PORT }}
