# Generated by Django 4.2.7 on 2023-12-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(default='-', max_length=250)),
                ('website', models.CharField(default='N/A', max_length=250)),
                ('contact_number', models.CharField(default='000-000-0000', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='source_currency',
            fields=[
                ('source_currency_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='target_currency',
            fields=[
                ('target_currency_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='exchange_rate',
            fields=[
                ('exchange_rate_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_update', models.DateTimeField()),
                ('source_currency_id', models.ForeignKey(db_column='source_currency_id', on_delete=django.db.models.deletion.CASCADE, to='BankFinder.source_currency')),
                ('target_currency_id', models.ForeignKey(db_column='target_currency_id', on_delete=django.db.models.deletion.CASCADE, to='BankFinder.target_currency')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('branch_contact_number', models.CharField(max_length=15)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('bank_id', models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, to='BankFinder.bank')),
            ],
        ),
        migrations.CreateModel(
            name='bank_exchange_rate',
            fields=[
                ('exchange_rate_id', models.ForeignKey(db_column='exchange_rate_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BankFinder.exchange_rate')),
                ('rate', models.FloatField()),
                ('last_update', models.DateTimeField()),
                ('bank_id', models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, to='BankFinder.bank')),
            ],
        ),
    ]
