# Generated by Django 4.2.7 on 2023-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='exchange_rate',
            name='exchange_rate_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='source_currency',
            name='source_currency_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='target_currency',
            name='target_currency_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
