# Generated by Django 4.2.7 on 2023-12-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0002_alter_bank_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
