# Generated by Django 5.0 on 2024-01-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0003_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.ImageField(default='default/default_bank.png', upload_to='banks/'),
        ),
    ]
