# Generated by Django 5.0 on 2024-01-04 20:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0004_bank_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='exchange_rate',
            name='source_currency_id',
        ),
        migrations.RemoveField(
            model_name='exchange_rate',
            name='target_currency_id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='bank_id',
            field=models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='BankFinder.bank'),
        ),
        migrations.CreateModel(
            name='bank_currency_exchange',
            fields=[
                ('currency_id', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BankFinder.currency')),
                ('rate', models.FloatField()),
                ('last_update', models.DateTimeField(default=datetime.datetime(2024, 1, 4, 16, 26, 19, 108422), null=True)),
                ('bank_id', models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, to='BankFinder.bank')),
            ],
        ),
        migrations.DeleteModel(
            name='bank_exchange_rate',
        ),
        migrations.DeleteModel(
            name='source_currency',
        ),
        migrations.DeleteModel(
            name='exchange_rate',
        ),
        migrations.DeleteModel(
            name='target_currency',
        ),
    ]
