# Generated by Django 4.2.6 on 2024-01-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0004_bank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bank_id',
            field=models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='BankFinder.bank'),
        ),
    ]
