# Generated by Django 5.0 on 2024-01-04 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0007_alter_bank_currency_exchange_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 16, 47, 5, 789138), null=True),
        ),
    ]
