# Generated by Django 5.0 on 2024-01-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0005_alter_branch_bank_id'),
        ('BankFinder', '0008_alter_bank_currency_exchange_last_update'),
    ]

    operations = [
    ]
