# Generated by Django 5.0 on 2024-01-10 18:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0009_merge_20240109_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='bank_id',
            field=models.ForeignKey(db_column='bank_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='BankFinder.bank'),
        ),
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 14, 12, 8, 710499), null=True),
        ),
    ]
