# Generated by Django 5.0 on 2024-01-10 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0010_alter_bank_currency_exchange_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 14, 23, 32, 649409), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bank_currency_exchange',
            unique_together={('bank_id', 'currency_id')},
        ),
    ]
