# Generated by Django 5.0 on 2024-01-11 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0012_alter_bank_currency_exchange_last_update'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bank_currency_exchange',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='bank_id',
            field=models.ForeignKey(db_column='bank_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='BankFinder.bank'),
        ),
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='currency_id',
            field=models.ForeignKey(db_column='currency_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='BankFinder.currency'),
        ),
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
