# Generated by Django 5.0 on 2024-01-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0013_alter_bank_currency_exchange_unique_together_and_more'),
    ]

    operations = [
    ]
