# Generated by Django 5.0 on 2024-01-11 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0016_alter_bank_currency_exchange_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 12, 59, 34, 703352), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bank_currency_exchange',
            unique_together={('bank_id', 'currency_id')},
        ),
    ]
