# Generated by Django 5.0 on 2024-01-18 18:51

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):
  dependencies = [ ('BankFinder', '0017_alter_bank_currency_exchange_last_update_and_more'),] # Add your dependencies here
  operations = [UnaccentExtension()]