# Generated by Django 5.0 on 2024-01-18 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0018_auto_20240118_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_currency_exchange',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
