# Generated by Django 5.0 on 2024-01-18 19:43

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('BankFinder', '0019_alter_bank_currency_exchange_last_update'),
    ]

    operations = [
        TrigramExtension()
    ]
