# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the whole project to the working directory
COPY . .

# Set environment variables
ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Create and activate a virtual environment
RUN python -m venv $VIRTUAL_ENV
RUN pip install --upgrade pip

# Install any needed packages directly from your project
RUN pip install --no-cache-dir -r requirements.txt  # Adjust the path accordingly

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["bash", "-c", "source /venv/bin/activate && cd server && python manage.py runserver 0.0.0.0:8000"]
